config/routes.rb
Rails.application.routes.draw do
  resources :testcategories
  devise_for :users
root to: "home#index"
get "/test/submit" => "home#test"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test , optional: true
  has_many :answers
  	 	  accepts_nested_attributes_for :answers

end

app/models/test.rb
class Test < ApplicationRecord
	  belongs_to :testcategory, optional: true
	 has_many :questions
	
	 	  accepts_nested_attributes_for :questions

end

app/models/testcategory.rb
class Testcategory < ApplicationRecord
		  has_many :tests
	  accepts_nested_attributes_for :tests
	  	 	


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		    @testcategory = Testcategory.new
             @tests=Test.all
	end

	def test

  @test = Test.find(params[:testid])
		
	end
end

app/controllers/testcategories_controller.rb
class TestcategoriesController < ApplicationController
  before_action :set_testcategory, only: [:show, :edit, :update, :destroy]

  # GET /testcategories
  # GET /testcategories.json
  def index
    @testcategories = Testcategory.all
  end

  # GET /testcategories/1
  # GET /testcategories/1.json
  def show
  end

  # GET /testcategories/new
  def new
    @testcategory = Testcategory.new
  end

  # GET /testcategories/1/edit
  def edit
  end

  # POST /testcategories
  # POST /testcategories.json
  def create
    @testcategory = Testcategory.new(testcategory_params)
     @testcategory.user_id = current_user.id
    respond_to do |format|
      if @testcategory.save
        format.html { redirect_to @testcategory, notice: 'Testcategory was successfully created.' }
        format.json { render :show, status: :created, location: @testcategory }
      else
        format.html { render :new }
        format.json { render json: @testcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testcategories/1
  # PATCH/PUT /testcategories/1.json
  def update
    respond_to do |format|
      if @testcategory.update(testcategory_params)
        format.html { redirect_to @testcategory, notice: 'Testcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @testcategory }
      else
        format.html { render :edit }
        format.json { render json: @testcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testcategories/1
  # DELETE /testcategories/1.json
  def destroy
    @testcategory.destroy
    respond_to do |format|
      format.html { redirect_to testcategories_url, notice: 'Testcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testcategory
      @testcategory = Testcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testcategory_params
      params.require(:testcategory).permit(:testcategoryname, :testname ,tests_attributes: [:id, :testname, :_destroy,   :qname ,questions_attributes: [:id, :qname, :_destroy, :aname ,answers_attributes: [:id, :aname, :_destroy]] ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/testcategories_helper.rb
module TestcategoriesHelper
end

app/views/home/index.html.erb
<%#= form_with(model: @testcategory, local: true) do |form| %>
<%if current_user.admin == true%>
<%= nested_form_for @testcategory do |form| %>
  <% if @testcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testcategory.errors.count, "error") %> prohibited this testcategory from being saved:</h2>

      <ul>
      <% @testcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :testcategoryname %>
    <%= form.text_field :testcategoryname, id: :testcategory_testcategoryname %>
  </div>






<%= form.fields_for :tests do |task_form| %>
  <%= task_form.text_field :testname %>
  <%= task_form.link_to_remove "Remove this test" %>
 



 <%= task_form.fields_for :questions do |task| %>
  <%= task.text_field :qname %>
  <%= task.link_to_remove "Remove this question" %>



<%= task.fields_for :answers do |task1| %>
  <%= task1.check_box :aname %>
  <%= task1.link_to_remove "Remove this answer" %>
<% end %>
<p><%= task.link_to_add "Add an answer", :answers %></p>




<% end %>
<p><%= task_form.link_to_add "Add an question", :questions %></p>







<% end %>
<p><%= form.link_to_add "Add an test", :tests %></p>








  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>









<%else%>


<% @tests.each do |test| %>
   
     <%= link_to "#{test.testname}", test_submit_path(testid: test) %>
   
  <% end %>
  <% end %>

app/views/home/test.html.erb
   
     <%#= link_to "#{test.testname}", test_submit_path(testid: test) %>
     <%@test.questions.each do |question|%>
    <%=question.qname%>
   <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BitternTestAsheesh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %> 
   <%#= link_to "profile", user_profile_path(id: current_user.id) %>       
  </li>
       <%# unless params[:controller] == "users" && params[:action] == "show" %>

  <%#= link_to "profile", {:controller => "users", :action => "show", :id => current_user.id }%>
  <%#end%>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/testcategories/_form.html.erb
<%= form_with(model: testcategory, local: true) do |form| %>
  <% if testcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testcategory.errors.count, "error") %> prohibited this testcategory from being saved:</h2>

      <ul>
      <% testcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :testcategoryname %>
    <%= form.text_field :testcategoryname, id: :testcategory_testcategoryname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testcategories/edit.html.erb
<h1>Editing Testcategory</h1>

<%= render 'form', testcategory: @testcategory %>

<%= link_to 'Show', @testcategory %> |
<%= link_to 'Back', testcategories_path %>

app/views/testcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testcategories</h1>

<table>
  <thead>
    <tr>
      <th>Testcategoryname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testcategories.each do |testcategory| %>
      <tr>
        <td><%= testcategory.testcategoryname %></td>
        <td><%= link_to 'Show', testcategory %></td>
        <td><%= link_to 'Edit', edit_testcategory_path(testcategory) %></td>
        <td><%= link_to 'Destroy', testcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testcategory', new_testcategory_path %>

app/views/testcategories/new.html.erb
<h1>New Testcategory</h1>

<%= render 'form', testcategory: @testcategory %>

<%= link_to 'Back', testcategories_path %>

app/views/testcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Testcategoryname:</strong>
  <%= @testcategory.testcategoryname %>
</p>

<%= link_to 'Edit', edit_testcategory_path(@testcategory) %> |
<%= link_to 'Back', testcategories_path %>